### ISSUE TITLE
Path error in reproduction test when run via docker container

### ISSUE THREAD

**Issue by TomMonks** [pythonhealthdatascience/stars-reproduce-lim-2020#1]
PASSED: docker container built correctly and launched!

PASSED: build docker container + `pytest`

FAILED: `scripts/reproduction.ipynb` 
* DESC:  runtime error. If I have understood correctly this is because it is trying to access ../../original_study/[CSV file]. But docker container launches notebook in reproduction/ as the root (i.e. it can't go ../../original study...).

Options:
* Launch Jupyter lab at one level higher than reproduction/ or duplicate CSV files in reproduction directory.

**Comment by amyheather** [comment]
Resolved in commit [a0612be](https://github.com/pythonhealthdatascience/stars-reproduce-lim-2020/commit/a0612be4c90b221b434c530dc9c3921da3961f16)
